### ISSUE TITLE
A small problem about the tags query

### ISSUE THREAD

**Issue by InnocenseYu** [erazlogo/obsidian-history-vault#6]
Hello, Elena

Thank you very much for your time on this project, it helped a lot, but I found a small problem.

The **tags:: field** of the file "meta/dataview/Search Research Notes.md" does not retrieve tags according to the content filled in, no matter what is filled in, the search results are all files under dv.pages('"folder"')

**Comment by erazlogo** [comment]
Are you adding the # sign before the tag? You need to enter the exact tag, including the # sign and also the full path for nested tags.

**Comment by InnocenseYu** [comment]
> Are you adding the # sign before the tag?

Indeed, as you say, the '#' is missing. Getting used to the yaml syntax
